version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: segstream/Dockerfile
    env_file:
      - segstream/.env
    command:
      - /bin/sh
      - -c
      - |
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./segstream:/code
    ports:
      - "8000:8000"

  webserver:
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./static/:/static/
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf:ro
