version: '3'

services:
  backend:
    build: ./segstream/
    command:
      - /bin/sh
      - -c
      - |        
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    restart: always

  webserver:
    build:
      context: .
      dockerfile: webserver/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/staticfiles/:/staticfiles/
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf:ro
